name:                bfck
version:             0.1.0.0
github:              "XDracam/brainfuck-haskell"
license:             BSD3
author:              "Cameron Reuschel"
maintainer:          "reuschel.cameron@live.com"
copyright:           "2018 Cameron Reuschel"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/XDracam/brainfuck-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- lens

library:
  source-dirs: src

executables:
  bfck-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bfck

tests:
  bfck-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bfck
    - HUnit
    - random
